### PR TITLE
Gh pages review 1

### PR DESCRIPTION
**Pull request by ovr**

### CODE REVIEW

**Comment by ovr** [comment]
Test before merge plz

**Comment by ovr** [comment]
@adamjacobbecker ping

**Comment by ajb** [comment]
Thanks, I will try and review this this weekend.

On Thu, Mar 27, 2014 at 3:31 AM, äÍÉÔÒÉÊ ðÁÃÕÒÁ notifications@github.comwrote:

> @adamjacobbecker https://github.com/adamjacobbecker ping
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/dobtco/jquery-resizable-columns/pull/22#issuecomment-38775602
> .

## 

Adam Becker
510.928.9111
@AdamJacobBecker

**Comment by ovr** [comment]
@adamjacobbecker ping

**Comment by ajb** [comment]
Thanks again. Sorry for the delay in merging!

:stars:

**Pull request merged**
